import "./globals.css";
import {
    ClerkProvider,
} from '@clerk/nextjs'
import { Toaster } from "@/components/ui/toaster"

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="bg-gray-100">
                <ClerkProvider>
                    <Toaster/>
                    {children}
                </ClerkProvider>
            </body>

        </html>
    )
}
